### ISSUE TITLE
Contact us: Hide map section if address is empty.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Air-Yoga#102]
![image](https://cloud.githubusercontent.com/assets/11186313/15036560/25ba2d58-12c3-11e6-8567-2e29a84d8d8f.png)

**Comment by ricatitan** [comment]
Address and "view in Google Maps" should also hide
![image](https://cloud.githubusercontent.com/assets/18568310/15135008/1d58ba32-16a4-11e6-8c97-7e243f8c7815.png)

**Comment by ricatitan** [comment]
"Address" must also be hidden in the pre-footer section.
![image](https://cloud.githubusercontent.com/assets/18568310/15136542/f48e539e-16b4-11e6-930e-b76dc5b73b8b.png)
