### ISSUE TITLE
Homepage- Video: Incorrect video size.

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Air-Yoga#15]
It should have 455px by 390px base on the design
![image](https://cloud.githubusercontent.com/assets/18568310/14909026/5203dab4-0e11-11e6-86a6-33f0cc668eed.png)

**Comment by roseliesromeo** [comment]
![image](https://cloud.githubusercontent.com/assets/11186313/15069832/e9a9d8c2-13b2-11e6-980d-e7c960a36926.png)
