### ISSUE TITLE
Homepage-Subscribe to our newsletter: Incorrect margin size for the button

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Air-Yoga#23]
It should have at least 150px by 46px base on the design
![image](https://cloud.githubusercontent.com/assets/18568310/14909780/c69a9fe0-0e19-11e6-92e3-384d1076446e.png)

**Comment by mikay-titan** [comment]
Design error.

**Comment by roseliesromeo** [comment]
Position button at the center of the section
