### ISSUE TITLE
Class Pricing: Incorrect font family

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Air-Yoga#45]
font size = 28px ; font color = #cc5e51 base on the design
![image](https://cloud.githubusercontent.com/assets/18568310/14945617/99afdd58-1047-11e6-9970-24579005ba2a.png)

font size= 43px base on the design
![image](https://cloud.githubusercontent.com/assets/18568310/14945623/aaad0ad6-1047-11e6-8437-ccf7e274add8.png)

font size= 25px
![image](https://cloud.githubusercontent.com/assets/18568310/14945628/b6a6b440-1047-11e6-85a4-cf998dc7ada8.png)

**Comment by roseliesromeo** [comment]
Font color not fixed
