### ISSUE TITLE
Class Pricing:  Missing "Buy Now" button

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Air-Yoga#46]
![image](https://cloud.githubusercontent.com/assets/18568310/14945656/3a374b80-1048-11e6-94d9-2ba4a9aaf546.png)

**Comment by mikay-titan** [comment]
Not a bug. "Buy Now" button will only display when a healcode is added in the admin. (Healcode 3rd party system for the scheduling of the classes)
