### ISSUE TITLE
Class Pricing- Membership: No "Buy Now " button

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Air-Yoga#51]
![image](https://cloud.githubusercontent.com/assets/18568310/14945794/bb8cd25c-104a-11e6-8f28-1caa36c7c62b.png)

**Comment by mikay-titan** [comment]
Not a bug. "Buy Now" will only show when a healcode is added in the admin. (Healcode 3rd party system for the scheduling of the classes)
