### ISSUE TITLE
Our Schedule Page: Inconsistent design. Incorrect font size, background color, text properties, etc.

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Air-Yoga#53]
Please see the design. Same error in class pricing page in our schedule.

![image](https://cloud.githubusercontent.com/assets/18568310/14945991/06dd2326-104e-11e6-963f-b2b2198637ab.png)

**Comment by mikay-titan** [comment]
Unable to style everything according to the design since it's a 3rd party system

**Comment by roseliesromeo** [comment]
Plug-in issue
