### ISSUE TITLE
Homepage- Subscribe to our news letter: Textbox is being highlighted by red 

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Air-Yoga#68]
It shouldn't be highlighted by red 
![image](https://cloud.githubusercontent.com/assets/18568310/14948127/932e77f0-106f-11e6-80db-765f618eb520.png)

**Comment by mikay-titan** [comment]
Not a bug. It's highlighted red because it's a validation error when the form was submitted.

**Comment by ricatitan** [comment]
This is not an invalid issue.
As you can see on the screenshot above, the name field has a valid value yet it was highlighted as an error field. Please check the new screenshot below.

![image](https://cloud.githubusercontent.com/assets/18568310/15068560/c2163ec0-13aa-11e6-9c7d-769e666aa931.png)
