### ISSUE TITLE
Our Classes: Image not fit in the circle.

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Air-Yoga#69]
It occurs in ie browser
![image](https://cloud.githubusercontent.com/assets/18568310/14948495/6c260f70-1073-11e6-9e2d-0c7ab0007ec1.png)

**Comment by roseliesromeo** [comment]
![image](https://cloud.githubusercontent.com/assets/11186313/15069260/0b372908-13af-11e6-8ad6-a70117d88e43.png)

**Comment by roseliesromeo** [comment]
Not fixed in IE
