### ISSUE TITLE
Our schedule: Error in mouse hover. Dropdown should be below the field

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Air-Yoga#70]
It occurs in i.e , edge browser. Should be 
![image](https://cloud.githubusercontent.com/assets/18568310/14948587/c4028b64-1074-11e6-815e-a20b59c4dd3d.png)
 Should be like this
![image](https://cloud.githubusercontent.com/assets/18568310/14948627/11ec00ee-1075-11e6-8f9f-de54fe633f6f.png)

**Comment by ronadtitan** [comment]
browser rendering issue
