### ISSUE TITLE
Our Blog: Error in mouse hover. Dropdown should be below the field

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Air-Yoga#72]
![image](https://cloud.githubusercontent.com/assets/18568310/14949270/3d18af32-107b-11e6-8a04-4e5e3d46135f.png)
 should be like this
![image](https://cloud.githubusercontent.com/assets/18568310/14949274/427c2620-107b-11e6-85bb-ae530ee19fa7.png)

**Comment by ronadtitan** [comment]
browser rendering issue
