### ISSUE TITLE
Our Story Page: Content page not aligned

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Air-Yoga#86]
![image](https://cloud.githubusercontent.com/assets/18568310/14973767/bebade7c-111e-11e6-8b8f-7dc3ede9c23a.png)

**Comment by mikay-titan** [comment]
![our-story](https://cloud.githubusercontent.com/assets/19181230/15061666/82be3aba-136a-11e6-8a6f-be0a91174ec9.jpg)

User content error. There's a class "row" inside WYSIWYG content.
