### ISSUE TITLE
Sitemap: No thank you page found

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Air-Yoga#94]
![image](https://cloud.githubusercontent.com/assets/18568310/14976315/1c07304e-113d-11e6-8ac2-4db3acecb7f6.png)

**Comment by mikay-titan** [comment]
Removed pages that is not defined in the Project Scope.

**Comment by roseliesromeo** [comment]
All forms should redirect to a Thank you page as the confirmation.

**Comment by roseliesromeo** [comment]
All forms should redirect to a thank you page as the notification.
